CREATE TABLE IF NOT EXISTS b_smith_b2b_company_user
(
    ID INT NOT NULL AUTO_INCREMENT,
    COMPANY_ID INT NOT NULL,
    COMPANY_USER_ID INT,
    COMPANY_MANAGER_ID INT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_smith_b2b_company_props
(
    ID INT NOT NULL AUTO_INCREMENT,
    COMPANY_LK_ID INT NOT NULL,
    OWNERSHIP_TYPE VARCHAR(5) NOT NULL,
    NAME VARCHAR(255),
    BRAND VARCHAR(255),
    INN VARCHAR(60) NOT NULL,
    OGRN VARCHAR(60),
    KPP VARCHAR(60),
    ADDRESS VARCHAR(255),
    PRIMARY KEY (ID),
    index IXS_COMPANY_COMPANY_LK_ID(COMPANY_LK_ID)
);

CREATE TABLE IF NOT EXISTS b_smith_b2b_company_store
(
    ID INT NOT NULL AUTO_INCREMENT,
    COMPANY_ID INT NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    NAME VARCHAR(60) NOT NULL,
    PHONE VARCHAR(60),
    EMAIL VARCHAR(60),
    PRIMARY KEY (ID),
    index IXS_COMPANY_STORE_COMPANY_ID(COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS b_smith_b2b_manager_for_store
(
    ID INT NOT NULL AUTO_INCREMENT,
    STORE_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (ID),
    index IXS_MANAGER_FOR_STORE_STORE_ID(STORE_ID)
);

CREATE TABLE IF NOT EXISTS b_smith_b2b_trade_agreement_grop
(
    ID INT NOT NULL AUTO_INCREMENT,
    COMPANY_ID INT NOT NULL,
    CATALOG_GROUP_ID INT NOT NULL,
    PRICE_GROUP_ID INT NOT NULL,
    DATE_BEGIN DATE,
    DATE_END DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_smith_b2b_trade_agreement_individual
(
    ID INT NOT NULL AUTO_INCREMENT,
    COMPANY_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRICE FLOAT NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    DATE_BEGIN DATE,
    DATE_END DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_smith_b2b_group
(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_smith_b2b_group_product
(
    ID INT NOT NULL AUTO_INCREMENT,
    GROUP_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (ID)
);